#=======================================================================================================================
         cmake_minimum_required(VERSION 4.2.0)
#=======================================================================================================================
         project(game_framework VERSION 0.0.1 LANGUAGES CXX)
#=======================================================================================================================
  add_executable(game_framework WIN32)
#=======================================================================================================================
          option(ENABLE_EDITOR_FEATURES "Enable Editor Features" ON) # TODO remove this? or put it in some other place
#=======================================================================================================================
add_subdirectory(modules)
#=======================================================================================================================
add_subdirectory(runtime)
#=======================================================================================================================