#=======================================================================================================================
             cmake_minimum_required(VERSION 4.2.0)
#=======================================================================================================================
         project(graphics_framework VERSION 0.0.1 LANGUAGES CXX)
#=======================================================================================================================
  add_executable(graphics_framework WIN32)
#=======================================================================================================================
          option(ENABLE_EDITOR_FEATURES "Enable Editor Features" ON)
#=======================================================================================================================
add_subdirectory(modules)
#=======================================================================================================================
add_subdirectory(runtime)
#=======================================================================================================================