#=======================================================================================================================
         cmake_minimum_required(VERSION 4.2.0)
#=======================================================================================================================
         project(game_framework VERSION 0.0.1 LANGUAGES CXX)
#=======================================================================================================================
  add_executable(game_framework WIN32)
#=======================================================================================================================
add_subdirectory(main)
#=======================================================================================================================
add_subdirectory(modules)
#=======================================================================================================================